// Generated by CoffeeScript 1.10.0
(function() {
  describe("APM Application", function() {
    var app;
    app = null;
    beforeEach(function() {
      return app = new ApmApplication('apm-main');
    });
    it("is initialized", function() {
      return expect(app.initialized).toBe(true);
    });
    return it("has a main-section", function() {
      return expect(app.css_id).toEqual("apm-main");
    });
  });

}).call(this);
